### ISSUE TITLE
:dev image issues

### ISSUE THREAD

**Issue by shamoon** [paperless-ngx/builder#10]
@stumpylog, a few issues with the current `:dev` image, .e.g. after last merge into dev: https://github.com/paperless-ngx/paperless-ngx/actions/runs/2111879700:

1. Even though https://github.com/paperless-ngx/builder/blob/7b4ffe517c9391599a5fce742ef2ee30cd2a5129/Dockerfile.base#L51 the current base image doesnt include that and fails on `pg_isready`
2. It's using the current (old) frontend
3. Interestingly, I also let a "feature" build run which works (i.e. fixes both of the above), see https://github.com/paperless-ngx/paperless-ngx/pkgs/container/paperless-ngx/18608524?tag=feature-django4-csrf
4. However, our top-level packages page now shows that feature branch at the top as opposed to latest. (Im not sure if this has anything to do with the builder).

Of course, thanks as always for all the work 🙏

<img width="801" alt="Screen Shot 2022-04-07 at 11 27 26 PM" src="https://user-images.githubusercontent.com/4887959/162379477-a875a975-2d08-4f84-9087-ce3a3f9e9e3c.png">

 (sorry I dont have more investigating to share, I wonder if you'll see the issue a lot faster than I could)

**Comment by stumpylog** [comment]
1. It'll take me a bit to setup a stack to test postgres.  Do you have the error handy?  is the command not found?
2. I can't imagine the base image affects the frontend in any way, that's all built by the main repo.  How can you tell its old?
3. Maybe it's a sort of race conditions between the two, but that's strange indeed
4. That's just Github, newer tags will show towards the top, older ones at the bottom or hidden.  It also doesn't cleanup tags when branches are deleted, we'd need to automate or manually do that.

**Comment by shamoon** [comment]
1. Yea just the `command not found` error ie implying the client wasn’t installed.
2. I know it’s not the dev frontend because it’s missing stuff that’s on dev.
3. Yea I’m confused why the feature branch worked and dev didn’t.
4. Ok thanks!

**Comment by stumpylog** [comment]
1. I just finished pulling both the `:dev` tags.  In both, `which pg_isready` told me it was there.  Setting up a compose stack, everything looked functional
2. What files can i check in the image or UI?  I'm a neophyte of anything Javascript or frontend
3. I'd still lean towards some sort of race condition where one dev hadn't yet finished building.  Except Postgres client tools have been in the image for a while...

**Comment by stumpylog** [comment]
I don't know if this is consistent, but my image info from `docker image ls` looked like this:
`ghcr.io/paperless-ngx/paperless-ngx     dev             2c6d82b034c6   17 hours ago    1.25GB`

**Comment by qcasey** [comment]
Yep `ghcr.io/paperless-ngx/paperless-ngx                         dev                        2c6d82b034c6   17 hours ago     1.25GB`

**Comment by shamoon** [comment]
Yea Im now seeing the same thing. Well, no idea how to figure out how that happened but obviously glad it just kinda sorted itself out... Thanks for all the checking dudes.
